name: merchant_repository
description: A repository that manages merchant data and menu items.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0

  # Utilities
  equatable: ^2.0.5
  uuid: ^4.5.1 # Useful for generating unique IDs for menu items

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
